name: app_flutter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  # Rango de SDK actualizado para Flutter 3.x/Dart 3.x (ej. >=3.0.0). 
  # Esto corrige el valor obsoleto de 3.9.2.
  sdk: '>=3.0.0 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter

# 1. Para peticiones HTTP a tu API
  http: ^1.1.0 
  
  # 2. Para abrir Google Maps (url locator)
  url_launcher: ^6.2.1 
  
  # 3. Para obtener la ubicación GPS (REQUERIDO)
  geolocator: ^11.0.0
  
  # 4. Para tomar la fotografía de evidencia (REQUERIDO)
  image_picker: ^1.0.7 # Usaremos la simulación de captura

  # Se unifica a una sola entrada la dependencia de iconos
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Se mantiene la versión de lints
  flutter_lints: ^2.0.0 # Se actualizó a una versión común (el 5.0.0 es excesivo para la mayoría de los proyectos) 

flutter:
  # Esta línea ya estaba correcta
  uses-material-design: true